export const actionTypes = {
    GET_CONTACT:"GET_CONTACT_SUCCESS",
    GET_CONTACT_LOADING:"GET_CONTACT_LOADING",
    GET_CONTACT_FAIL:"GET_CONTACT_FAIL",
    POST_BOOK:"POST_BOOK_SUCCESS",
    UPDATA_BOOK:"UPATA_BOOK_BY_ID",
    DELETE_BOOK:"DELETE_BOOK_BY_ID",
    SELECT_BOOK:"SELECT_BOOK_BY_ID",
    REMOVE_SELECT_BOOK:"REMOVE_SELECT_BOOK"
}